version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9 # ジョブ実行環境のDockerイメージを記述
    working_directory: ~/repo

    steps:
      - checkout # ソースコードのチェックアウト
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json"}}
          - v1-dependencies-

      - run: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json"}}
      # run test
      - run: yarn test
      - run: yarn build
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

