version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9 # ジョブ実行環境のDockerイメージを記述
    working_directory: ~/repo

    steps:
      - checkout # ソースコードのチェックアウト
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12.9 # ジョブ実行環境のDockerイメージを記述
    working_directory: ~/repo
    steps:
      - checkout # ソースコードのチェックアウト
      - run: yarn install
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:12.9 # ジョブ実行環境のDockerイメージを記述
    working_directory: ~/repo
    steps:
      - checkout # ソースコードのチェックアウト
      - run: yarn install
      - run: yarn build
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              - master
